# Generated by Django 4.1.5 on 2023-01-30 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flight',
            name='airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='management.airplane'),
        ),
        migrations.AddField(
            model_name='flight',
            name='from_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_airport', to='management.airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city', to='management.city'),
        ),
        migrations.AddField(
            model_name='flight',
            name='option',
            field=models.ManyToManyField(to='management.option'),
        ),
        migrations.AddField(
            model_name='flight',
            name='to_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_airport', to='management.airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_city', to='management.city'),
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='management.city'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='management.city'),
        ),
    ]
