# Generated by Django 4.1.5 on 2023-02-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='service_type',
            field=models.CharField(choices=[('included', 'Included'), ('extra', 'Extra')], max_length=8, null=True),
        ),
    ]
