# Generated by Django 4.1.5 on 2023-02-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_option_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='boarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='service_type',
            field=models.CharField(choices=[('extra', 'Extra'), ('included', 'Included')], max_length=8, null=True),
        ),
    ]
