# Generated by Django 4.1.5 on 2023-02-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_ticket_boarding_alter_option_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='option',
            name='service_type',
            field=models.CharField(choices=[('included', 'Included'), ('extra', 'Extra')], max_length=8, null=True),
        ),
    ]
