import * as  alert from 'bootstrap/js/dist/alert'
import * as  base_component from 'bootstrap/js/dist/base-component'
import * as  button from 'bootstrap/js/dist/button'
import * as  carousel from 'bootstrap/js/dist/carousel'
// import * as  collapse from 'bootstrap/js/dist/collapse'
import * as  dropdown from 'bootstrap/js/dist/dropdown'
import * as  modal from 'bootstrap/js/dist/modal'
// import * as  offcanvas from 'bootstrap/js/dist/offcanvas'
// import * as  popover from 'bootstrap/js/dist/popover'
// import * as  scrollspy from 'bootstrap/js/dist/scrollspy'
// import * as  tab from 'bootstrap/js/dist/tab'
// import * as  toast from 'bootstrap/js/dist/toast'
// import * as  tooltip from 'bootstrap/js/dist/tooltip'
